### ISSUE TITLE
deixar imagens redondas

### ISSUE THREAD

**Issue by OkagawaTheo** [TM-Time/Python#11]
> Alo @Miguel-Perfume deixa essas imagens redondas .png por favor
 <>pull request da mt trabalho
>marca a caixa qnd tiver feito por favor
- [x] _done_

# IMAGENS
![silhouette-photography-of-electric-post-and-houses-2282315](https://user-images.githubusercontent.com/63313909/86163887-4c632880-bae7-11ea-9b3a-870d7eeec4ae.jpg)
![nature-sky-clouds-blue-53594 (1)](https://user-images.githubusercontent.com/63313909/86163893-4ec58280-bae7-11ea-86a7-e0720ac90d7b.jpg)
![astronomy-comet-constellation-cosmos-631477](https://user-images.githubusercontent.com/63313909/86163899-508f4600-bae7-11ea-88ac-bb15543fb4db.jpg)

**Comment by Miguel-Perfume** [comment]
@OkagawaTheo pronto

![deixaissoredodo1 2](https://user-images.githubusercontent.com/66442554/86164070-91875a80-bae7-11ea-8948-694bdb40b410.png)

![deixaredondo2 2](https://user-images.githubusercontent.com/66442554/86164074-92b88780-bae7-11ea-93b6-291339c81b0d.png)

![deixaredondo3 2](https://user-images.githubusercontent.com/66442554/86164075-92b88780-bae7-11ea-8531-0194019f5ea2.png)
