### ISSUE TITLE
Deixar imagens menores

### ISSUE THREAD

**Issue by OkagawaTheo** [TM-Time/Python#12]
> Alo @Miguel-Perfume deixe aquelas imagens que te mandei mais cedo um pouco menor por favor
>250px ta bom
- [x] _done_

**Comment by Miguel-Perfume** [comment]
feliz agora?

![fiadaputs](https://user-images.githubusercontent.com/66442554/86165211-60a82500-bae9-11ea-92c6-bbf7dc95241a.png)

![fiadaputs2](https://user-images.githubusercontent.com/66442554/86165219-63a31580-bae9-11ea-847e-b2929505a3ee.png)

![fiadaputs3](https://user-images.githubusercontent.com/66442554/86165222-63a31580-bae9-11ea-9c3a-0624d7a95939.png)

**Comment by OkagawaTheo** [comment]
obrigado paitola

s2
